### PR TITLE
fixes json parse error, fixes early event emitting when model still not ready on file uploaded and another place

### PR DESCRIPTION
**Pull request by romain10009**
Hello, this is my first pull request ever. I fixed some JSON parsing error by catching the error. This error happens when I have the server offline and try to upload a file. Also i saw two places where the type of the file was set after the broadcast off events. I could also add an autoupload fonction later if you dont mind.

### CODE REVIEW

**Comment by Wildhoney** [comment]
Thanks @romain10009 but could you make your changes in the [`components/ngDroplet.js` file](https://github.com/Wildhoney/ngDroplet/blob/master/components/ngDroplet.js) and then re-commit? Once you've made the change in that file, the build process will compile the `dist` files :+1:

**Comment by romain10009** [comment]
yes i saw my error, doing a new commit ; )

**Comment by Wildhoney** [comment]
Your IDE seems to have done something peculiar with the files, which makes diffing them very difficult. You just need to modify the `components/ngDroplet.js` file, and when you open the pull request, it should only show the difference on a handful of lines that you've changed.

This can happen in some circumstances where your IDE is setup to use different whitespace than the original files, and so when you open the file, for example, it replaces all 4-spaces with tabs.

Perhaps the best way to solve this is to close this PR, and then start again with forking the repository, and modifying **only** the lines you wish to change. Careful not to modify the whitespace of the rest of the file. Alternatively you could `git revert` the changes in this PR.

Let me know if you need any help :+1:

**Comment by Wildhoney** [comment]
Any updates on this PR, @romain10009?

**Comment by romain10009** [comment]
I'm gonna do a new PR.

**Pull request closed without merging**
